org: devisnotnull
service: fandanzle-pure-ui

frameworkVersion: ">=2.0.0"
variablesResolutionMode: 20210326
plugins:
  - serverless-offline
  - serverless-deployment-bucket
  - serverless-prune-plugin
  - serverless-s3-sync

custom:
  ##
  localDevStaticFolder: build

  ## Retention
  prune:
    automatic: true
    includeLayers: true
    number: 10

  ## 
  deploymentBucket:
    versioning: true
    accelerate: true

  ## S3 bucket for static assets
  s3Sync:
    - bucketName: ${self:service}-${self:custom.environment}
      bucketPrefix: static/
      localDir: build/static
    - bucketName: ${self:service}-${self:custom.environment}
      bucketPrefix: media/
      localDir: media
  ##
  environment: ${opt:stage, 'development'}

## 
package:
  exclude:
    - .cache/**
    - .github/**
    - node_modules/**
    - src/**

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 10 
  region: ${opt:region, 'eu-west-2'}
  stackName: ${self:service}-${self:custom.environment}
  environment:
    NODE_RUNTIME_ENV: ${self:custom.environment}

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:custom.environment}
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
              MaxAge: 3000
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: MyPolicy
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref AssetsBucket
                  - /*
        Bucket: !Ref AssetsBucket
    