name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      run: yarn install
    - name: yarn build:dev
      run: yarn build:dev
    - name: yarn build:prod
      run: yarn build:prod

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fandanzle-v2:$(date +%s) --tag fandanzle-v2:latest
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: alexbrown201/fandanzle-v2
        tags: latest
